[pytest]
addopts = --alluredir=allure-results --tb=short -v
filterwarnings = ignore::DeprecationWarning
markers =
    smoke: marks tests as smoke tests
    regression: marks tests as regression tests
    api: marks tests as API tests
    ui: marks tests as UI tests 